"""add_position_to_subgoals

Revision ID: 887c652cb6b1
Revises: 1335f514f1b9
Create Date: 2026-04-12 20:29:56.478135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887c652cb6b1'
down_revision: Union[str, None] = '1335f514f1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgoals', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subgoals', 'position')
    # ### end Alembic commands ###
